on : [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Dai'
    - name: output the memory
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "totoal memory successfully output"
